[package]
name = "snapshot-editor"
version = "1.18.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "snapshot-editor"
bench = false

[features]
tracing = ["log-instrument", "fc_utils/tracing", "vmm/tracing"]

[dependencies]
clap = { version = "4.6.1", default-features = false, features = [
    "std",
    "help",
    "usage",
    "error-context",
    "derive",
    "string",
] }
displaydoc = { version = "0.2.6", default-features = false, features = ["std"] }

fc_utils = { package = "utils", path = "../utils" }
libc = { version = "0.2.186", default-features = false, features = ["std"] }
log-instrument = { path = "../log-instrument", optional = true }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
vmm = { path = "../vmm" }
vmm-sys-util = { version = "0.15.0", default-features = false }

[target.'cfg(target_arch = "aarch64")'.dependencies]
clap-num = { version = "1.2.0", default-features = false }

[lints]
workspace = true
