[workspace]
members = ["src/*"]
# We exclude the jailer below so that it does not get build by default. This is because "cargo build" compiles
# for the gnu target, and the jailer needs a statically compiled binary to work correctly.
# See https://github.com/firecracker-microvm/firecracker/commit/3bf285c8f8a815149923c562dd7edaffcaf10c4e
# and https://github.com/firecracker-microvm/firecracker/issues/2102
default-members = [
    "src/clippy-tracing",
    "src/cpu-template-helper",
    "src/firecracker",
    "src/rebase-snap",
    "src/seccompiler",
    "src/snapshot-editor",
    "src/acpi-tables",
]
resolver = "2"

[workspace.lints.rust]
missing_debug_implementations = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[workspace.lints.clippy]
cast_lossless = "warn"
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_ptr_alignment = "warn"
cast_sign_loss = "warn"
char_lit_as_u8 = "warn"
fn_to_numeric_cast = "warn"
fn_to_numeric_cast_any = "warn"
fn_to_numeric_cast_with_truncation = "warn"
ptr_as_ptr = "warn"
unnecessary_cast = "warn"
undocumented_unsafe_blocks = "warn"
exit = "warn"
tests_outside_test_module = "warn"
assertions_on_result_states = "warn"
error_impl_error = "warn"
or_fun_call = "warn"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
strip = "none"

[profile.bench]
strip = "debuginfo"
