#!/bin/sh

# Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# We avoid checks which require building firecracker due to the issues this introduces when 
# attempting to interact with the repository from an enviroment in which you cannot build 
# firecracker.

# This will only fail when a staged file does not contain an appropriate license
# when formatting is incorrect this will automaticalt rectify it.

# Exit immediately when encountering a non-zero command
set -e

# Audit code base
cargo audit
# Format rust code
cargo fmt
# For every staged file
for i in $(git diff --name-only --cached --diff-filter=d); do
    echo $i
    # Get the extension
    filename=$(basename -- "$i")
    extension="${filename##*.}"
    # If python
    if [ "$extension" = "py" ]; then
        # Run `black` to format this file
        black $i
    fi
    # Add changes to this file (as a result of formatting) to the commit.
    git add $i
done
