[package]
name = "cpu-template-helper"
version = "1.17.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "cpu-template-helper"
bench = false

[features]
tracing = ["log-instrument", "vmm/tracing"]

[dependencies]
clap = { version = "4.6.1", default-features = false, features = [
    "std",
    "help",
    "usage",
    "error-context",
    "derive",
    "string",
] }
displaydoc = { version = "0.2.6", default-features = false, features = ["std"] }
libc = { version = "0.2.186", default-features = false, features = ["std"] }
log-instrument = { path = "../log-instrument", optional = true }
serde = { version = "1.0.228", default-features = false, features = [
    "std",
    "derive",
] }
serde_json = { version = "1.0.150", default-features = false, features = [
    "std",
] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }

vmm = { path = "../vmm" }
vmm-sys-util = { version = "0.15.0", default-features = false }

[lints]
workspace = true
