#!/bin/bash

if [ ! $# -eq 1 ]; then
    >&2 echo "Usage: $0 <repo_path>"
    exit 1
fi

REPO_PATH=$1
CRATE_DIR_REL_PATHS=`find . -type f -name '*Cargo.toml' | sed -r 's|/[^/]+$||'`

for crate_dir_rel_path in ${CRATE_DIR_REL_PATHS}; do
    ${REPO_PATH}/scripts/unit_test_coverage/gen-code-coverage-for-crate $REPO_PATH $crate_dir_rel_path
done
