#!/bin/bash

mkdir -p target/cov/build
LCOVOPTS="--gcov-tool llvm-gcov --rc lcov_branch_coverage=1"
LCOVOPTS="${LCOVOPTS} --rc lcov_excl_line=assert"
lcov ${LCOVOPTS} --capture --directory . --base-directory . \
    -o target/cov/build/raw.lcov
lcov ${LCOVOPTS} --extract target/cov/build/raw.lcov "$(pwd)/*" \
    -o target/cov/build/raw_crate.lcov

mkdir -p target/cov/report
genhtml --branch-coverage --legend \
    -o target/cov/report/ \
    target/cov/build/raw_crate.lcov
