[package]
name = "firecracker"
version = "1.18.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
build = "build.rs"
description = "Firecracker enables you to deploy workloads in lightweight virtual machines, called microVMs, which provide enhanced security and workload isolation over traditional VMs, while enabling the speed and resource efficiency of containers."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[lib]
bench = false

[[bin]]
name = "firecracker"
bench = false

[features]
tracing = ["log-instrument", "utils/tracing", "vmm/tracing"]
fuzzing = ["vmm/fuzzing"]
gdb = ["vmm/gdb"]

[dependencies]
displaydoc = { version = "0.2.6", default-features = false, features = ["std"] }
event-manager = { version = "0.4.2", default-features = false }
libc = { version = "0.2.186", default-features = false, features = ["std"] }
log-instrument = { path = "../log-instrument", optional = true }
micro_http = { git = "https://github.com/firecracker-microvm/micro-http", default-features = false }
serde = { version = "1.0.228", default-features = false, features = [
    "std",
    "derive",
] }
serde_json = { version = "1.0.150", default-features = false, features = [
    "std",
] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
utils = { path = "../utils" }
vmm = { path = "../vmm" }
vmm-sys-util = { version = "0.15.0", default-features = false, features = [
    "with-serde",
] }

[build-dependencies]
seccompiler = { path = "../seccompiler" }
serde = { version = "1.0.228", default-features = false, features = ["std"] }
serde_json = { version = "1.0.150", default-features = false, features = [
    "std",
] }

[dev-dependencies]
cargo_toml = { version = "1.0.0", default-features = false }
libc = { version = "0.2.186", default-features = false, features = ["std"] }
semver = { version = "1.0.28", default-features = false, features = ["std"] }

# Dev-Dependencies for uffd examples
serde = { version = "1.0.228", default-features = false, features = [
    "std",
    "derive",
] }
userfaultfd = { version = "0.9.0", default-features = false }

[lints]
workspace = true

[[example]]
name = "uffd_malicious_handler"
path = "examples/uffd/malicious_handler.rs"

[[example]]
name = "uffd_on_demand_handler"
path = "examples/uffd/on_demand_handler.rs"

[[example]]
name = "uffd_fault_all_handler"
path = "examples/uffd/fault_all_handler.rs"

[[example]]
name = "seccomp_harmless"
path = "examples/seccomp/harmless.rs"

[[example]]
name = "seccomp_jailer"
path = "examples/seccomp/jailer.rs"

[[example]]
name = "seccomp_malicious"
path = "examples/seccomp/malicious.rs"

[[example]]
name = "seccomp_panic"
path = "examples/seccomp/panic.rs"
