[package]
name = "seccompiler"
version = "1.17.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
description = "Program that compiles multi-threaded seccomp-bpf filters expressed as JSON into raw BPF programs, serializing them and outputting them to a file."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[lib]
bench = false

[[bin]]
name = "seccompiler-bin"
path = "src/bin.rs"
bench = false

[dependencies]
bitcode = { version = "0.6.9", default-features = false, features = [
    "std",
    "serde",
] }
clap = { version = "4.6.1", default-features = false, features = [
    "std",
    "help",
    "usage",
    "error-context",
    "derive",
    "string",
] }
displaydoc = { version = "0.2.6", default-features = false, features = ["std"] }
libc = { version = "0.2.186", default-features = false, features = ["std"] }
serde = { version = "1.0.228", default-features = false, features = [
    "std",
    "derive",
] }
serde_json = { version = "1.0.150", default-features = false, features = [
    "std",
] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
zerocopy = { version = "0.8.50", default-features = false }

[lints]
workspace = true
