[advisories]
ignore = [
    # The `paste` dependency is transitively included via `gdbstub`.
    # While the crate is archived/unmaintained, the author considers it feature-complete
    # and functionally stable. gdbstub will be update once they migrate
    # to an alternative solution.
    # See https://github.com/daniel5151/gdbstub/issues/168
    "RUSTSEC-2024-0436",

    # `anyhow` is not directly used by any of our crates. It is a transitive
    # dependency of build-time WASM tooling (wit-bindgen).
    # See https://rustsec.org/advisories/RUSTSEC-2026-0190.html
    "RUSTSEC-2026-0190",
]
