// Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// automatically generated by tools/bindgen.sh

#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    non_snake_case,
    clippy::ptr_as_ptr,
    clippy::undocumented_unsafe_blocks,
    missing_debug_implementations,
    clippy::tests_outside_test_module
)]

pub const HV_X64_MSR_SYNDBG_CONTROL: u32 = 0x400000f1;
pub const HV_X64_MSR_SYNDBG_STATUS: u32 = 0x400000f2;
pub const HV_X64_MSR_SYNDBG_SEND_BUFFER: u32 = 0x400000f3;
pub const HV_X64_MSR_SYNDBG_RECV_BUFFER: u32 = 0x400000f4;
pub const HV_X64_MSR_SYNDBG_PENDING_BUFFER: u32 = 0x400000f5;
pub const HV_X64_MSR_SYNDBG_OPTIONS: u32 = 0x400000ff;
