[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
license = "Apache-2.0"

[lib]
bench = false

[features]
tracing = ["log-instrument"]

[dependencies]
displaydoc = { version = "0.2.6", default-features = false, features = ["std"] }
libc = { version = "0.2.186", default-features = false, features = ["std"] }
log-instrument = { path = "../log-instrument", optional = true }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }

[lints]
workspace = true
