/* automatically generated by rust-bindgen */

pub const VIRTIO_ID_NET: ::std::os::raw::c_uint = 1;
pub const VIRTIO_ID_BLOCK: ::std::os::raw::c_uint = 2;
pub const VIRTIO_ID_CONSOLE: ::std::os::raw::c_uint = 3;
pub const VIRTIO_ID_RNG: ::std::os::raw::c_uint = 4;
pub const VIRTIO_ID_BALLOON: ::std::os::raw::c_uint = 5;
pub const VIRTIO_ID_RPMSG: ::std::os::raw::c_uint = 7;
pub const VIRTIO_ID_SCSI: ::std::os::raw::c_uint = 8;
pub const VIRTIO_ID_9P: ::std::os::raw::c_uint = 9;
pub const VIRTIO_ID_RPROC_SERIAL: ::std::os::raw::c_uint = 11;
pub const VIRTIO_ID_CAIF: ::std::os::raw::c_uint = 12;
pub const VIRTIO_ID_GPU: ::std::os::raw::c_uint = 16;
pub const VIRTIO_ID_INPUT: ::std::os::raw::c_uint = 18;
pub const VIRTIO_ID_VSOCK: ::std::os::raw::c_uint = 19;
pub const VIRTIO_ID_CRYPTO: ::std::os::raw::c_uint = 20;
