[package]
name = "jailer"
version = "1.17.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
description = "Process for starting Firecracker in production scenarios; applies a cgroup/namespace isolation barrier and then drops privileges."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[[bin]]
name = "jailer"
bench = false

[features]
tracing = ["log-instrument", "utils/tracing"]

[dependencies]
libc = { version = "0.2.186", default-features = false, features = ["std"] }
log-instrument = { path = "../log-instrument", optional = true }
regex = { version = "1.12.3", default-features = false, features = ["std"] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
vmm-sys-util = { version = "0.15.0", default-features = false }

utils = { path = "../utils" }

[lints]
workspace = true
