[package]
name = "log-instrument-macros"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
description = "Offers an attribute procedural macro that adds `log::trace!` events at the start and end of attributed functions."
license = "Apache-2.0"

[lib]
proc-macro = true
bench = false

[dependencies]
proc-macro2 = { version = "1.0.106", default-features = false, features = [
    "proc-macro",
] }
quote = { version = "1.0.45", default-features = false, features = [
    "proc-macro",
] }
syn = { version = "3.0.2", default-features = false, features = [
    "clone-impls",
    "parsing",
    "printing",
    "proc-macro",
    "full",
    "extra-traits",
] }

[lints]
workspace = true
