[package]
name = "clippy-tracing"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "clippy-tracing"
bench = false

[dependencies]
clap = { version = "4.6.1", default-features = false, features = [
    "std",
    "help",
    "usage",
    "error-context",
    "derive",
] }
itertools = { version = "0.15.0", default-features = false, features = [
    "use_std",
] }
proc-macro2 = { version = "1.0.106", default-features = false, features = [
    "proc-macro",
    "span-locations",
] }
quote = { version = "1.0.45", default-features = false, features = [
    "proc-macro",
] }
syn = { version = "3.0.2", default-features = false, features = [
    "clone-impls",
    "parsing",
    "printing",
    "proc-macro",
    "full",
    "extra-traits",
    "visit",
    "visit-mut",
] }
walkdir = { version = "2.5.0", default-features = false }

[dev-dependencies]
uuid = { version = "1.23.2", default-features = false, features = [
    "std",
    "v4",
] }

[lints]
workspace = true
